### ISSUE TITLE
Any audio example?

### ISSUE THREAD

**Issue by chapykiller** [KinglittleQ/GST-Tacotron#1]
Do you have any audio example generated using griffin-lim or wavenet? How many iterations until an audible output?

**Comment by KinglittleQ** [comment]
I have uploaded 3 samples just now. They were generated by the model trained on a 3-speakers Chinese dataset with 100 epochs.

**Comment by Young-Sun** [comment]
Nice work :-)
Have you ever experimented experiments using LJ datasets? If yes, could you upload samples?
Why did you set the number of heads as 8?
