### ISSUE TITLE
what‘s Length of training corpus？

### ISSUE THREAD

**Issue by peter05010402** [KinglittleQ/GST-Tacotron#3]
@KinglittleQ  Thank you share out！
what‘s Length of training corpus？

**Comment by KinglittleQ** [comment]
The training text can be of any length, but it's better to be in the range of 5 to 30.

**Comment by peter05010402** [comment]
Thank you for your reply!
Then could u help me: how to  train or get "Reference encoder"?
![reference_encoder](https://user-images.githubusercontent.com/42974031/47558534-f3241880-d945-11e8-91e1-56be46614b3f.JPG)

**Comment by KinglittleQ** [comment]
The code of `reference encoder ` is in `GST.py`.
