### ISSUE TITLE
Does your training dataset contains reference audio?

### ISSUE THREAD

**Issue by liangshuang1993** [KinglittleQ/GST-Tacotron#4]
Hi KinglittleQ,

In your Data.py file, there's `wav_dirs = ['nannan', 'xiaofeng', 'donaldduck']`. So does your training dataset contains reference audio? Have you tried using different data? Thanks!

**Comment by KinglittleQ** [comment]
Hi EchoLiang,

My training data contains the reference audio. I didn't try to use other
reference audios and I think it won't work well because there are only 3
different people voice in training dataset where origin paper used hundreds
or thousands of different people voice.

Thanks.

**Comment by liangshuang1993** [comment]
Hi @KinglittleQ ,

I have finished training on thchs30 dataset(Combining your gst code with another tacotron version).

It can use other reference audio, but the results are not always good. I wonder if you did any further research, like controlling each style token?  In my case, only 3 style token can make some obvious influence. 

Thanks for you answer.

**Comment by KinglittleQ** [comment]
I didn't try to control the style token and add this function. You can have a try.
