### ISSUE TITLE
The evaluation is ineffective on Biaobei corpus

### ISSUE THREAD

**Issue by begeekmyfriend** [KinglittleQ/GST-Tacotron#6]
The attention gets alignment but the evaluation is not match the style of reference speakers. Did you try this model on Biaobei open corpus?
By the way, [here](http://www.data-baker.com/open_source.html) is biaobei open dataset download link. The corpus is produced from a single female anchor.
[biaobei_eval.zip](https://github.com/KinglittleQ/GST-Tacotron/files/2873847/biaobei_eval.zip)
![epoch722-donaldduck](https://user-images.githubusercontent.com/6031938/52924964-f23a4b00-3369-11e9-922c-6af4a9b39312.png)
![epoch722-nannan](https://user-images.githubusercontent.com/6031938/52924971-f8302c00-3369-11e9-97b3-835a77350208.png)
![epoch722-xiaofeng](https://user-images.githubusercontent.com/6031938/52924921-cd45d800-3369-11e9-870d-1ca53b565a26.png)

**Comment by yxt132** [comment]
@begeekmyfriend did you figure out the reason? I am looking at the code in "gst.py". I am confused by the dimensions of the "query_dim" and "key_dim". Why is query_dim equal to "hp.E // 2" and  key_dim equal to "hp.E // hp.num_heads"? Should they both be "hp.E"?

**Comment by begeekmyfriend** [comment]
In `GST.py` you can see there are three parametric matries for all the query, key and value and therefore the dimensions of the outputs which will be used to calculate in the attention mechanism are the same.
```python
self.W_query = nn.Linear(in_features=query_dim, out_features=num_units, bias=False)
self.W_key = nn.Linear(in_features=key_dim, out_features=num_units, bias=False)
self.W_value = nn.Linear(in_features=key_dim, out_features=num_units, bias=False)
```

**Comment by yxt132** [comment]
> In `GST.py` you can see there are three parametric matries for all the query, key and value and therefore the dimensions of the outputs which will be used to calculate in the attention mechanism are the same.
> 
> ```python
> self.W_query = nn.Linear(in_features=query_dim, out_features=num_units, bias=False)
> self.W_key = nn.Linear(in_features=key_dim, out_features=num_units, bias=False)
> self.W_value = nn.Linear(in_features=key_dim, out_features=num_units, bias=False)
> ```

Thank you @begeekmyfriend. I listened to your audio examples. All three are like the same person. I wonder if single-speaker training corpus is not adequate for style transfer. What's your computation configuration (i.e. gpu number and type, batch size, time takes to learn alignment)?

**Comment by begeekmyfriend** [comment]
Single GPU, batch size as 32, and very quick to alignment < 10 epoches.

**Comment by yxt132** [comment]
that is very impressive. I am trying to get it work using Tacotron 2 with the same training corpus as yours. I have 6 GPUs and I am not able to learn good alignment after 2 days. Below is the alignment and there are just isolated pieces. Weird. Did you try GST with Tacotron 2? 
<img width="586" alt="2019-02-22 9 41 08" src="https://user-images.githubusercontent.com/43161328/53214118-6173b000-3686-11e9-9dea-638a515519bc.png">

**Comment by KinglittleQ** [comment]
@begeekmyfriend How many different people voices does biaobei dataset contain?  I trained my model on a dataset which contains 3 different people voices with about 10000 sentences of each.

**Comment by begeekmyfriend** [comment]
@KinglittleQ Just single speaker. Does GST Tacotron need multi-speakers for training? Moreover what about male reference speaker containing female speaker?

**Comment by KinglittleQ** [comment]
@begeekmyfriend  Of course, it needs multi-speakers data. GST-Tacotron learns voice styles from different speakers. For more details, refer to the original [paper](https://arxiv.org/abs/1803.09017).
